### ISSUE TITLE
Plugin Default global variables trigger a warning on flow editor

### ISSUE THREAD

**Issue by Vinceveve** [kestra-io/vscode-kestra#20]
When I set on helm charts plugin defaults. Or when I configure on my flow pluginDefaults.

The tasks using this pluginDefault are marked as warning because the variable are not set in the task (they are on pluginDefaults)

Tasks are working well, it's just a warning on the IDE

![CleanShot 2024-10-24 at 15 40 03@2x](https://github.com/user-attachments/assets/2e55cad6-abb6-4c3c-9716-f61c2a0eef3a)

**Comment by Ben8t** [comment]
hi @Vinceveve, thanks for raising this issue. Can you provide your Kestra version please ?

**Comment by Vinceveve** [comment]
latest 0.19.4

**Comment by Vinceveve** [comment]
The behavior is on the embeded editor and on visual studio code extension

**Comment by anna-geller** [comment]
Reproducer:
```yaml
id: repro_defaults
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log

pluginDefaults:
  - type: io.kestra.plugin.core.log.Log
    values:
      message: Hello World! 🚀
```

<img width="4112" height="1722" alt="Image" src="https://github.com/user-attachments/assets/f1760784-c1c8-45ef-bf2c-a0f67d861b7a" />
